---
http_interactions:
- request:
    method: patch
    uri: http://tuneapp.localhost/api/inventory/1
    body:
      encoding: UTF-8
      string: '{"name":"Inventory Item","inventory_type_id":1,"part_number":"1234","sku":"1234","notes":"here
        are some notes","part_price":"19.99","location_id":2,"quantity":1}'
    headers:
      Accept:
      - application/json
      User-Agent:
      - TuneupTechnologyApp/RubyClient/
      Email:
      - "<API_EMAIL>"
      Api-Key:
      - "<API_KEY>"
      Content-Length:
      - '161'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Host:
      - tuneapp.localhost
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache, private
      Content-Type:
      - application/json
      Date:
      - Sat, 12 Jun 2021 00:46:22 GMT
      Server:
      - nginx
      X-Powered-By:
      - PHP/7.4.15
      X-Ratelimit-Limit:
      - '60'
      X-Ratelimit-Remaining:
      - '52'
      Content-Length:
      - '256'
    body:
      encoding: UTF-8
      string: '{"id":1,"name":"Inventory Item","quantity":1,"created_at":"2021-06-12
        00:44:58","updated_at":"2021-06-12 00:46:22","deleted_at":null,"inventory_type_id":1,"part_number":"1234","sku":"1234","notes":"here
        are some notes","part_price":"19.99","location_id":2}'
  recorded_at: Sat, 12 Jun 2021 00:46:22 GMT
recorded_with: VCR 6.0.0
